// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package user

import (
	"github.com/jun3372/weaver/runtime/codegen"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "github.com/jun3372/weaver/examples/hello/user/User",
		Interface: reflect.TypeOf((*User)(nil)).Elem(),
		Impl:  reflect.TypeOf(user{}),
	})
}
