// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package udp

import (
	"github.com/jun3372/weaver/runtime/codegen"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:      "github.com/jun3372/weaver/examples/http/udp/T",
		Interface: reflect.TypeFor[T](),
		Impl:      reflect.TypeFor[impl](),
	})
}

// Check that impl implements the T interface.
var _ T = (*impl)(nil)
