// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package main

import (
	"github.com/jun3372/weaver"
	"github.com/jun3372/weaver/runtime/codegen"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:      "github.com/jun3372/weaver/Main",
		Interface: reflect.TypeFor[weaver.Main](),
		Impl:      reflect.TypeFor[app](),
	})
	codegen.Register(codegen.Registration{
		Name:      "github.com/jun3372/weaver/examples/echo/all/T",
		Interface: reflect.TypeFor[T](),
		Impl:      reflect.TypeFor[gateway](),
	})
}

// Check that app implements the weaver.Main interface.
var _ weaver.Main = (*app)(nil)

// Check that gateway implements the T interface.
var _ T = (*gateway)(nil)
