// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package chat

import (
	"github.com/jun3372/weaver/runtime/codegen"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:      "github.com/jun3372/weaver/examples/hello/chat/Chat",
		Interface: reflect.TypeFor[Chat](),
		Impl:      reflect.TypeFor[chat](),
	})
}

// Check that chat implements the Chat interface.
var _ Chat = (*chat)(nil)
